name: Build and Deploy

on:
  push:
    branches:
      - main   # или твоя ветка

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и пуш образов
      - name: Build and push parserochek
        run: |
          docker build -t yanterbrown44/parserochek:latest -f MpParserAPI/Dockerfile .
          docker push yanterbrown44/parserochek:latest

      - name: Build and push bot
        run: |
          docker build -t yanterbrown44/tgbotik:latest -f MpBossParserNotification/Dockerfile .
          docker push yanterbrown44/tgbotik:latest

      # 4. Деплой на сервер через SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d
